blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (
    url(r'^$', views.post_list, name='post_list'),
    url(r'^books/(?P<slug>[\w./-]+)/$', views.books, name='books'),
    url(r'^(?P<slug>[\w./-]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<slug>[\w./-]+)/md$', views.serialize_text, name='serialize_text'),
    url(r'^(?P<slug>[\w./-]+)/update$', views.update, name='update_text'),
    url(r'^search', views.search_posts, name='search_posts'),
)

howto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^blog/', include('blog.urls', namespace='dynamicblog'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class BlogAuthor(models.Model):
    """ a customized/extended User profile """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    github_name = models.CharField(max_length=250, blank=True)
    redmine_name = models.CharField(max_length=250, blank=True)
    website = models.URLField(blank=True)
    image = models.FileField(upload_to='author_img', blank=True, null=True)

    def __str__(self):
        return self.user.username

    def image_name(self):
        return os.path.basename(self.image.name)


class Book(models.Model):
    """ A 'Book' groups a series of blogs"""
    editor = models.ForeignKey(BlogAuthor, related_name='book_editor')
    title = models.CharField(max_length=250)
    summary = models.TextField(blank=True)
    slug = models.SlugField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to='book_img', blank=True, null=True)
    book_color = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ('title', )

    def __str__(self):
        return self.title

    def image_name(self):
        return os.path.basename(self.image.name)


class Post(models.Model):
    """A Blog-Post objects"""

    STATUS_CHOICES = (
        ('draft', 'draft'),
        ('published', 'published')
    )

    ENCODING_CHOICES = (
        ('TEI', 'TEI'),
        ('markdown', 'markdown')
    )

    AUDIENCE_CHOICES = (
        ('ACDH-CORE', 'ACDH-CORE'),
        ('ACDH-EXTENDED', 'ACDH-EXTENDED'),
        ('PUBLIC', 'PUBLIC'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(BlogAuthor, related_name='blog_posts')
    summary = models.TextField(blank=True)
    body = models.TextField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='draft')
    audience = models.CharField(max_length=30, choices=AUDIENCE_CHOICES, default='ACDH-CORE')
    encoding = models.CharField(max_length=30, choices=ENCODING_CHOICES, default='markdown')
    repo_url = models.URLField(blank=True, max_length=300)
    github_url = models.URLField(blank=True, max_length=300)
    tags = TaggableManager()
    book = models.ForeignKey(Book, blank=True, null=True)

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('dynamicblog:post_detail', kwargs={'slug': self.slug})

blog/views.py
import markdown2
import requests
import lxml.etree as ET
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.templatetags.staticfiles import static
from haystack.query import SearchQuerySet
from django.http import HttpResponse
from .models import Post, Book


def search_posts(request):
    context = {}
    try:
        groupname = request.user.groups.all()[0].name
        if groupname == 'ACDH-CORE':
            usergroups = ['ACDH-CORE', 'ACDH-EXTENDED', 'PUBLIC']
        elif groupname == 'ACDH-EXTENDED':
            usergroups = ['ACDH-EXTENDED', 'PUBLIC']
    except:
        usergroups = ['PUBLIC']
    if 'q' in request.GET:
        searchstring = request.GET.get('q', '')
        results = SearchQuerySet().filter(content=searchstring, audience__in=usergroups).load_all()
        total_results = results.count()
    else:
        searchstring = None
        total_results = None
        results = None
    context['searchstring'] = searchstring
    context['total_results'] = total_results
    context['results'] = results
    return render(request, 'blog/blog_search.html', context)


def filter_posts_by_usergroups(user):
    """filters posts matching its audience target"""
    try:
        group = user.groups.all()[0].name
        if group == 'ACDH-CORE':
            posts = Post.objects.all()
        elif group == 'ACDH-EXTENDED':
            posts = Post.objects.filter(audience__in=['ACDH-EXTENDED', 'PUBLIC'])
    except:
        posts = Post.objects.filter(audience='PUBLIC')
    return posts


def tei_to_html(url, tei):
    """fetches as stylesheet from the given url and transforms an
    xslt transformation on the given TEI-encoded text"""
    try:
        r = requests.get(url)
        xslt = ET.XSLT(ET.fromstring(r.text))
        xml = ET.fromstring(tei)
        html = xslt(xml)
        result = ET.tostring(html)
    except:
        result = "unfortunately something went wrong"
    return result


def books(request, slug):
    book = get_object_or_404(Book, slug=slug)
    userobject = request.user
    posts = filter_posts_by_usergroups(userobject).filter(book=book)
    # posts = Post.objects.filter(book=book)
    context = {}
    context["object_list"] = posts
    context["book"] = book
    return render(request, 'blog/blog_list.html', context)


def post_list(request):
    userobject = request.user
    posts = filter_posts_by_usergroups(userobject)
    tags = []
    for x in posts:
        for y in x.tags.names():
            tags.append(y)
    context = {}
    context['object_list'] = posts
    context['tag_list'] = set(tags)
    return render(request, 'blog/blog_list.html', context)
    

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {}
    prefix = 'https://' if request.is_secure() else 'http://'
    url = prefix + request.get_host() + static('blog/xslt/tei-to-html.xsl')
    if post.encoding == "markdown":
        md_text = markdown2.markdown(post.body, extras=["fenced-code-blocks"])
        tei_text = None
    else:
        md_text = None
        tei_text = tei_to_html(url, post.body)
    context['object'] = post
    context['md_text'] = md_text
    context['tei_text'] = tei_text
    ''' check for auth or PUBLIC post '''
    if request.user.is_authenticated() or post.audience == 'PUBLIC':
        return render(request, 'blog/blog_detail.html', context)
    else:
        return render(request, 'blog/access_error.html')
    return render(request, 'blog/blog_detail.html', context)


def serialize_text(request, slug):
    post = get_object_or_404(Post, slug=slug)
    md_text = post.body
    response = HttpResponse(md_text, content_type="text/plain")
    response['Content-Disposition'] = 'attachment; filename="{}.md"'.format(slug)

    return response


@login_required
def update(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        url = request.POST.get('url', '')
        with requests.Session() as s:
            try:
                r = s.get(url)
                if r.status_code == requests.codes.ok:
                    print("past eh ois", r.status_code)
                    decoded_content = r.content.decode('utf-8')
                    post.body = decoded_content
                    post.save()
                    md_text = markdown2.markdown(post.body, extras=["fenced-code-blocks"])
                    return render(
                        request, 'blog/blog_detail.html',
                        {'object': post, 'md_text': md_text, 'updated': 'Text successfully updated'}
                    )
                else:
                    print("oho", r.status_code)
                    return render(
                        request, 'blog/blog_detail.html',
                        {'object': post, 'md_text': md_text, 'error': r.status_code}
                    )
            except:
                print("soemthing is wrong", url)
                md_text = markdown2.markdown(post.body, extras=["fenced-code-blocks"])
                return render(
                    request, 'blog/blog_detail.html',
                    {'object': post, 'md_text': md_text, 'error': 'something went wrong'})
    else:
        md_text = markdown2.markdown(post.body, extras=["fenced-code-blocks"])
        return render(request, 'blog/blog_detail.html', {'object': post, 'md_text': md_text})

blog/templates/blog/access_error.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}
Access restricted
{% endblock %}
{% block content %}
<h2>The post is only for registered users.<br>
If you have an account please login.</h2>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}
{{ object.slug }}
{% endblock %}
{% block scriptHeader %}
<link rel="stylesheet" href="{% static 'blog/css/colorful.css' %}"/></link>
<link rel="stylesheet" href="{% static 'blog/js/cool-share/plugin.css' %}"/></link>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
<script src="{% static 'blog/js/cool-share/plugin.js' %}"/></script>
<style>
  #content {
  text-align: justify;
  /*  margin-top: 100px;*/
  }
  #content  img {
  max-width:1000px;
  height:auto;
  margin: 25px auto;
  display:block
  }
  /*dynamic post-title*/
  {% if object.book_id %}
  .post-title--{{object.book_id}} {
  font-weight: bold;
  color: {{object.book.book_color}};
  }
  {% endif %}
   /*end of dynamic post-title*/

  .post-title--other {
    font-weight: bold;
   color: #587583;
  }
  .post-meta {
  font-style: italic;
  font-size: 18px;
 /* font-weight: 600;*/
    }
</style>
{% endblock %}
{% block content %}
{% if object.book_id %}
<h1 class="post-title--{{object.book_id}}">{{ object.title }}</h1>
{% else %}
<h1 class="post-title--other">{{ object.title }}</h1>
{% endif %}
<h3 class="post-meta"><b>Posted by</b> <a href="{{ object.author.website }}">{{ object.author }}</a><br/> on {{ object.created}} (last update {{ object.updated }})
            </h3>
<h4 class="post-meta"><b>status:</b> {{ object.status }}</h4>
{% if updated %}
{{ updated }}
{% endif %}

{% if error %}
{{ error }}
{% endif %}

{% if md_text %}
{{ md_text|safe }}
{% endif %}

{% if tei_text %}
{{ tei_text|safe }}
{% endif %}
<hr/>
{% if request.user.is_superuser %}
<form action="{% url 'dynamicblog:update_text' slug=object.slug %}" method="POST">
{% csrf_token %}
  <div class="form-group">
    <input type="hidden" class="form-control" id="email" required="true" name="url" value="{{ object.repo_url }}">
  </div>
  <button type="submit" class="btn btn-default" data-toggle="tooltip" title="{{ object.repo_url }}!">update</button>
</form>
{% endif %}
{% if object.github_url %}
Comment/Edit this post on <a href="{{ object.github_url }}">GitHub</a>.<br/>
{% endif %}
<a href="{% url 'dynamicblog:serialize_text' slug=object.slug %}">export blog text </a><br/>
<hr/>
<span class="socialShare"> <!-- The share buttons will be inserted here --> </span>
<script type="text/javascript">
  $(function (){
    var options = {
      twitter: {
        text: 'Read about "{{ object.title }}" here:',
        via: ''
      },
      facebook : true,
      googlePlus : true
    };
  $('.socialShare').shareButtons(options);
});

</script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}
Table of content
{% endblock %}
{% block scriptHeader %}
{% endblock %}
{% block content %}

<style>
.grid-item {
  float: left;

  padding-left: 20px;
  padding-right: 20px;
  padding-top: 20px;
  padding-bottom: 20px;
  position: relative;
}
/*clean if grid-item*/
{% for object in object_list %}
{% if object.book %}
.grid-item--{{object.book_id}} {
   margin: 1%;
    border: 5px solid {{object.book.book_color}};
    color: {{object.book.book_color}};
    float: left;
    width: calc(94% / 3);
    background-color: #ffffff;
    position: relative;
}

.grid-item.grid-item--{{object.book_id}}:hover,
.grid-item.grid-item--{{object.book_id}}:hover .post-title,
.grid-item.grid-item--{{object.book_id}}:hover .post-subtitle {
  background-color: {{object.book.book_color}};
  color:#ffffff;

}
.grid-item.grid-item--{{object.book_id}} .hrmain {
  border-color: {{object.book.book_color}};
}
.grid-item.grid-item--{{object.book_id}}:hover .hrmain {
  border-color: #ffffff;
}

.grid-item--{{object.book_id}} a {
  color:{{object.book.book_color}};
  text-decoration: none;
}
{% endif %}
{% endfor %}
/*end of clean grid-item*/

/*grid-item-no-book-id or no book_color*/
.grid-item--no-book-id {
    margin: 1%;
  border: 5px solid #587583;
  color: #587583;
  float: left;
  width: calc(94% / 3);
  background-color: #ffffff;
  position: relative;
}
.grid-item--no-book-id a {
  color:#587583;
  text-decoration: none;
}
.grid-item.grid-item--no-book-id:hover,
.grid-item.grid-item--no-book-id:hover .post-title,
.grid-item.grid-item--no-book-id:hover .post-subtitle {
  background-color: #587583;
  color:#ffffff;

}
.grid-item.grid-item--no-book-id .hrmain {
  border-color: #587583;
}
.grid-item.grid-item--no-book-id:hover .hrmain {
  border-color: #ffffff;
}

/*end of grid-item-no-book-id*/


.post-title {

  font-weight: bold;
}

.post-subtitle {
  color: #696969;
  font-weight: bold;
}
.book-image {
  border: 5px solid black;
  margin: 15px;
}



@media (min-width: 480px) and (max-width: 768px) {

  .grid-item { width: calc(94% / 2); }
  .book-image { width: 50% }
}
@media (max-width: 480px) {

  .grid-item { width: 94%; }
  .book-image { width: 50% }

}

#blogjumbo {
  background-color: #e7ecef;
}
.blog-name {
  font-weight: bold;
 /* border-bottom: 3px solid black;*/
}


/*for button in filtering */
.button {
  background-color: white;
  border: 2px solid #ccc;
  margin-bottom: 10px;
  padding: 12px 20px 12px 20px;
  white-space: normal;
}

.button:hover {
  background-color: #e7ecef;
  border-color: #ccc;
  color: #222;

}

.button:active,
.button.is-checked {
  background-color: #007bb4;
  border-color: #007bb4;
}

.button.is-checked {
  color: white;
  border-color: #007bb4;
  /*text-shadow: 0 -1px hsla(0, 0%, 0%, 0.8);*/
}

.button:active, .button.is-checked {
  /*box-shadow: inset 0 1px 10px hsla(0, 0%, 0%, 0.8);*/
  border-color: #007bb4;
  border-radius: 0;
}

.button-group .button {
  border-radius: 0;
}
#quicksearch {
    width: 40%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 0px;
    font-size: 16px;
    background-color: white;
    background-image: url({% static 'blog/img/search.png' %});
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
}

#quicksearch:focus {
    width: 60%;
}
</style>
<!--Mansory JS-->
<script type="text/javascript" src="https://npmcdn.com/masonry-layout@4.0.0/dist/masonry.pkgd.min.js"></script>
<div class="jumbotron text-center" id="blogjumbo">
{% if book %}
    <h1 class="blog-name">{{ book.title }}</h1>
    <p>{{ book.summary }}</p>
    {% if book.image %}
        <img src="{{ book.image.url }}" width="300" class="book-image"/>
    {% endif %}
    <p>edited by <a href="{{ book.editor.website }}">{{ book.editor }}</a></p>
{% else %}
  <h1 class="blog-name">HowTo</h1>
  <p>A blog about how to do things in Digital Humanities</p>
{% endif %}
</div>
<div class="text-center">
<div>
  {% if not book %}
  <h2>Filter by tags</h2>
  <div class="button-group filters-button-group" id="filters">
    <button class="button btn btn-default is-checked" data-filter="*">show all</button>
    {% for x in tag_list %}
    <button class="button btn btn-default" data-filter=".{{x}}">{{x}}</button>
    {% endfor %}
  </div>
  <p><input type="text" class="quicksearch" placeholder="Search" id="quicksearch"/></p>
  {% else %}
  <p><input type="text" class="quicksearch" placeholder="Search" id="quicksearch"/></p>
  {% endif %}
</div>
<div class="grid" >
        {% for object in object_list %}
        {% if object.book_id and object.book.book_color %}
        <div class="grid-item grid-item--{{object.book_id}} post-preview   {% for tag in object.tags.all %} {{ tag.name }} </li> {% endfor %}">
            <a href="{% url 'dynamicblog:post_detail' slug=object.slug %}">
                <h2 class="post-title" data-title="{{ object.title }}">
                    {{ object.title }}
                </h2>
            </a>
            <hr class="hrmain">
            <a href="{% url 'dynamicblog:post_detail' slug=object.slug %}">
            <h3 class="post-subtitle">
                {{ object.summary }}
            </h3>
            </a>
        </div>
        {% else %}
        <div class="grid-item grid-item--no-book-id post-preview   {% for tag in object.tags.all %} {{ tag.name }} </li> {% endfor %}">

            <a href="{% url 'dynamicblog:post_detail' slug=object.slug %}">
                <h2 class="post-title" data-title="{{ object.title }}">
                    {{ object.title }}
                </h2>
            </a>
            <hr class="hrmain">
            <a href="{% url 'dynamicblog:post_detail' slug=object.slug %}">
            <h3 class="post-subtitle">
                {{ object.summary }}
            </h3>
            </a>
        </div>
        {% endif %}
        {% endfor %}
  </div>
</div>
<!--Isotope-->
<script type="text/javascript">

$(window).on('load resize', function (){
$('.grid').isotope({
 itemSelector: '.grid-item',
});

});

// quick search regex
var qsRegex;
var buttonFilter;

// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.grid-item',
  // layoutMode: 'fitRows',
  filter: function() {
    var $this = $(this);
    var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;
    var buttonResult = buttonFilter ? $this.is( buttonFilter ) : true;
    return searchResult && buttonResult;
  }
});

$('#filters').on( 'click', 'button', function() {
  buttonFilter = $( this ).attr('data-filter');
  $grid.isotope();
});

// use value of search field to filter
var $quicksearch = $('#quicksearch').keyup( debounce( function() {
  qsRegex = new RegExp( $quicksearch.val(), 'gi' );
  $grid.isotope();
}) );


  // change is-checked class on buttons
$('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  $buttonGroup.on( 'click', 'button', function() {
    $buttonGroup.find('.is-checked').removeClass('is-checked');
    $( this ).addClass('is-checked');
  });
});
// debounce so filtering doesn't happen every millisecond
function debounce( fn, threshold ) {
  var timeout;
  return function debounced() {
    if ( timeout ) {
      clearTimeout( timeout );
    }
    function delayed() {
      fn();
      timeout = null;
    }
    setTimeout( delayed, threshold || 100 );
  };
}
</script>
{% endblock %}

blog/templates/blog/blog_search.html
{% extends 'webpage/base.html' %}
{% block Titel %}
    {% if 'q' in request.GET %}
        results for "{{ searchstring }}""
    {% else %}
        nothing searched for
    {% endif %}
{% endblock %}

{% block content %}
{% if 'q' in request.GET %}
<h2>{{ total_results }} Hit{{ total_results|pluralize }} for <strong>{{ searchstring }}</strong></h2>

{% for result in results %}
    {% with post=result.object %}
    <div>
        <h4>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h4>
        {{ post.summary }}
    </div>
    {% endwith %}
{% endfor %}

{% else %}
    <h2> no search </h2>
{% endif %}
   
{% endblock %}