blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (
    url(r'^$', views.post_list, name='post_list'),
    url(r'^books/(?P<slug>[\w./-]+)/$', views.books, name='books'),
    url(r'^(?P<slug>[\w./-]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<slug>[\w./-]+)/md$', views.serialize_text, name='serialize_text'),
    url(r'^(?P<slug>[\w./-]+)/update$', views.update, name='update_text'),
    url(r'^search', views.search_posts, name='search_posts'),
)

howto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^blog/', include('blog.urls', namespace='dynamicblog'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start_view, name="start"),
    url(r'^imprint/$', views.imprint_view, name='imprint'),
    url(r'^project-info/$', views.project_info, name='project_info'),
]

webpage/models.py
from django.db import models

# Create your models here.

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.core.urlresolvers import reverse
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div


class form_user_login(forms.Form):
	username = forms.CharField(label='Username',widget=forms.TextInput)
	password = forms.CharField(label='Password',widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		super(form_user_login, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.add_input(Submit('submit','Login'))

webpage/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .metadata import PROJECT_METADATA as PM
from copy import deepcopy


def start_view(request):
    if PM is not None:
        context = {"metadata": PM}
    else:
        context = {}

    return render(request, 'webpage/index.html', context)


def imprint_view(request):
    if PM is not None:
        context = {"metadata": PM}
    else:
        context = {}

    return render(request, 'webpage/imprint.html', context)


#################################################################
#                    project info view                          #
#################################################################


def project_info(request):

    """
    returns a dict providing metadata about the current project
    """

    info_dict = deepcopy(PM)
    if request.user.is_anonymous:
        del info_dict['matomo_id']
        del info_dict['matomo_url']
    else:
        pass    
    info_dict['base_tech'] = 'django'
    info_dict['framework'] = 'djangobaseproject'
    return JsonResponse(info_dict)

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block Titel %} About {% endblock %}

{% block content %}
    <div class="container">
        <h1>{% projects_metadata 'title' %}</h1>
    </div>
{% endblock %}

webpage/templates/webpage/base.html
{% load staticfiles %}
{% load webpage_extras %}
{% load account_extras %}
{% load blog_extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>{% block Titel %} {% projects_metadata 'title' %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block metaDescription %}
      <meta name="description" content="{{ metadata.description }}">
      {% endblock %}
      <meta name="author" content="{{ metadata.author }}">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap335/css/bootstrap.min.css' %}"/></link>
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}"/></link>
      <!--scroll to top CSS -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}"></link>
      <!-- jQuery -->
      <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
      <!--Isotop-->
      <script src="https://unpkg.com/isotope-layout@3.0/dist/isotope.pkgd.js"></script>
      <!--scroll to top -->
      <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
      <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
        <script type="text/javascript">
            window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"{% url 'webpage:imprint' %}","theme":"dark-bottom"};
        </script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
      <!-- End Cookie Consent plugin -->
      <!-- Piwik -->
        <script type="text/javascript">
         var _paq = _paq || [];
         _paq.push(["setDomains", ["*.howto.eos.arz.oeaw.ac.at"]]);
         _paq.push(['trackPageView']);
         _paq.push(['enableLinkTracking']);
         (function() {
           var u="//piwik.apollo.arz.oeaw.ac.at/";
           _paq.push(['setTrackerUrl', u+'piwik.php']);
           _paq.push(['setSiteId', '38']);
           var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
           g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
         })();
        </script>
        <noscript>
            <p><img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=38" style="border:0;" alt="" /></p>
        </noscript>
      <!-- End Piwik Code -->
<style>
html {
height: 100%;
}
body {
display: flex;
flex-direction: column;
height: 100%;
font-family: "Lato", sans-serif;
font-size: 18px;
padding-top: 70px;
}
.wrap {
  white-space: pre-wrap;      /* CSS3 */
  white-space: -moz-pre-wrap; /* Firefox */
  white-space: -pre-wrap;     /* Opera <7 */
  white-space: -o-pre-wrap;   /* Opera 7 */
  word-wrap: break-word;      /* IE */

}
header {
flex: 0 0 auto;
}
.main-content {
flex: 1 0 auto;
/*padding-top: 20px;*/
padding-bottom: 80px;
}
footer {
flex: 0 0 auto;
}
.navbar {
background-color: white;
font-weight: 900;
font-size: 20px;
padding: 10px;
/*border: none;*/
}
.navbar .navbar-brand {
  font-size: 20px;
  }
@font-face {
font-family: Lato;
src: url(https://fonts.gstatic.com/s/lato/v11/1YwB1sO8YE1Lyjf12WNiUA.woff2);
/*font-weight: bold;*/
/*font-weight: 900;*/
}
.navbar li a, .navbar .navbar-brand {
color: #242424 !important;
font-family: Lato;
}
.navbar-nav li a:hover, .navbar-nav li.active a, .navbar-brand:hover {
color: #f52c47 !important;
background-color: #ffffff !important;
}
/*.navbar-nav li a:active,
 .navbar-nav li a:visited,
 .navbar-nav li a:focus {
  color:#242424;
  background-color: #ffffff;
}*/
.navbar-default .navbar-nav>.open>a,
.navbar-default .navbar-nav>.open>a:hover,
.navbar-default .navbar-nav>.open>a:focus {
   color:#242424;
  background-color: #ffffff;
}
.navbar-brand, .navbar-nav li a {
line-height: 50px;
height: 50px;
padding-top:0;
}
.navbar-default .dropdown-menu {
  background-color: #ffffff;
}
.hrfooter {
  border-color: black;
  border-width: 2px;
}
.navlink img {
 padding-top: 10px;
 padding-bottom: 10px;

}

#footer-info {
  border-top: 2px solid #242424;
  padding-top: 40px;

}
#acdhlogo,
#ccbylogo {
  width: 50%;
}
#githublogo {
  width: 20%;
}
@media (max-width: 767px) {
      #acdhlogo,
      #ccbylogo {
          width: 15%;
      }
      #githublogo {
        width: 7%;
      }
  }

a {
  outline: 0;
}
a:focus {
  outline: 0;
}
#blogjumbo {
  background-color: #e7ecef;
}
.navbar-header > .navbar-toggle > .icon-bar {
  background-color: #242424;
}
</style>
      {% block scriptHeader %}
      {% endblock %}
  </head>

  <body role="document">
    <header>
     <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'dynamicblog:post_list' %}">HOW TO</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li>{% book_list %}</li>
      </ul>
      <div class="pull-right">
                    <form method="get" action="{% url 'dynamicblog:search_posts' %}" class="navbar-form" id="pageform">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="q"/>
                            </div>
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-search" aria-hidden="true" title="fulltext search over all documents"/>
                            </button>
                        </div>
                    </form>
                </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'webpage:start' %}">ABOUT</a></li>
        <li><a href="{% url 'webpage:imprint' %}">IMPRINT</a></li>
        <li class="dropdown">
                {% if user.is_authenticated %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"/>&nbsp;{{ user.get_username }}
                  </a>
                {% else %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"/>
                  </a>
                {% endif %}
                {% login_tag %}
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>
    <section class="main-content">

      <div id="content" class="container">
        {% block content %}
        {% endblock %}
      </div>

    </section>

    <footer>
<div class="container" >
  <div id="footer-info">
      <div class="row text-center">
        <div class="col-sm-3">
        <h4><span class="glyphicon glyphicon-map-marker"></span>  Vienna, Austria</h4>
<h4><span class="glyphicon glyphicon-envelope"></span>  acdh-tech@oeaw.ac.at </h4>


      </div>
        <div class="col-sm-3">
          <a href="https://www.oeaw.ac.at/acdh/" class="navlink">
              <img src="{% static 'webpage/img/acdh_logo_black_with_text.png' %}" alt="ACDH" id="acdhlogo" title="Austrian Centre for Digital Humanities"/>
          </a>
        </div>
        <div class="col-sm-3 ">
            <a href="{% projects_metadata 'github' %}" class="navlink">
              <img src="{% static 'webpage/img/GitHub-Mark-64px.png' %}" alt="{{ metadata.github }}" id="githublogo" title="ACDH Github"/>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="https://creativecommons.org/licenses/by-sa/4.0/" class="navlink">
              <img src="{% static 'webpage/img/by-sa.png' %}" alt="CC-BY-SA-4.0" id="ccbylogo" title="CC-BY-SA-4.0 license"/>
            </a>
        </div>

      </div>
    </div>
  </div>
  </footer>
    {% block scripts %}
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <!-- scroll-up-bottom -->
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>
    {% endblock %}
  </body>
</html>

webpage/templates/webpage/base_old.html
{% load staticfiles %}
{% load webpage_extras %}
{% load account_extras %}
{% load blog_extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>{% block Titel %} {% projects_metadata 'title' %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block metaDescription %}
      <meta name="description" content="{{ metadata.description }}">
      {% endblock %}
      <meta name="author" content="{{ metadata.author }}">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap335/css/bootstrap.min.css' %}"/></link>
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}"/></link>
      <!--scroll to top CSS -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}"></link>
      <!-- jQuery -->
      <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
      <!--scroll to top -->
      <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
      <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
        <script type="text/javascript">
            window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"{% url 'webpage:imprint' %}","theme":"dark-bottom"};
        </script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
      <!-- End Cookie Consent plugin -->
      <!-- Piwik -->
        <script type="text/javascript">
         var _paq = _paq || [];
         _paq.push(["setDomains", ["*.howto.eos.arz.oeaw.ac.at"]]);
         _paq.push(['trackPageView']);
         _paq.push(['enableLinkTracking']);
         (function() {
           var u="//piwik.apollo.arz.oeaw.ac.at/";
           _paq.push(['setTrackerUrl', u+'piwik.php']);
           _paq.push(['setSiteId', '38']);
           var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
           g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
         })();
        </script>
        <noscript>
            <p><img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=38" style="border:0;" alt="" /></p>
        </noscript>
<!-- End Piwik Code -->
      {% block scriptHeader %}
      {% endblock %}
  </head>

  <body role="document">
    <nav class="navbar navbar-default">
      <div class="container ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation!</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
        </div>  
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% projects_metadata 'title' %}
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'webpage:start' %}">{% projects_metadata 'title' %}</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:imprint' %}">Impressum / Imprint</a>
                    </li>
                  </ul>
                </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">dynamic-blog<span class="caret"/>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                          <a href="{% url 'dynamicblog:post_list' %}">Posts</a>
                      </li>
                    </ul>
                  </li>
                  {% book_list %}
              </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                {% if user.is_authenticated %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"/>&nbsp;{{ user.get_username }}
                  </a>
                {% else %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"/>
                  </a>
                {% endif %}
                {% login_tag %}
              </li>
            </ul>
        </div>
    </nav>
    <div class="alert alert-danger">
      <strong>Be Aware!</strong> This Site/Service is at a very early state of developement. Everything can change at any time.
    </div>

    <section class="main-content">
      <div id="content" class="container">
        {% block content %}
        {% endblock %}
      </div>
    </section>

    <footer>
      <div class="row text-center">
        <div class="col-sm-4">
          <a href="https://acdh.oeaw.ac.at/acdh/" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/ACDH_kurz_Weiss.png' %}" alt="ACDH" width="25%"/>   
          </a>
        </div>
        <div class="col-sm-4">
            <a href="{% projects_metadata 'github' %}" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/GitHub-Mark-Light-64px.png' %}" alt="{{ metadata.github }}" width="10%"/>   
            </a>
        </div>
        <div class="col-sm-4">
            <a href="https://creativecommons.org/licenses/by-sa/4.0/" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/by-sa.png' %}" alt="CC-BY-SA-4.0" width="25%"/>                 
            </a>
        </div>
      </div>  
    </footer>
    {% block scripts %}
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <!-- scroll-up-bottom -->        
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>
    {% endblock %}
  </body>
</html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}

<!-- Launch modal on page load http://stackoverflow.com/questions/10233550/launch-bootstrap-modal-on-page-load -->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Confirm delete</h3>
      </div>
      <div class="modal-body">
       	<form action="" method="post">{% csrf_token %}
    		<h4>Are you sure you want to delete the {{ object.get_classname }}:<br /> <strong>{{ object }}</strong> ?</h4>
    		<input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
		</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
{{block.super}}
<script type="text/javascript">
$(window).load(function(){
        $('#myModal').modal('show');
    });
</script>

{% endblock scripts %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block content %}

<div id="myCarousel" class="carousel slide" data-ride="carousel"><!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"/>
        <li data-target="#myCarousel" data-slide-to="1"/>
    </ol><!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'webpage/img/ACDH_Panorama_Postkarte_motiv01.jpg' %}" alt="First" width="1200" height="600" title="by Sandra Lehecka"/>
            <div class="carousel-caption"></div>
        </div>
        <div class="item">
            <img src="{% static 'webpage/img/ACDH_Panorama_Postkarte_motiv02.jpg' %}" alt="a nice feature picture" width="1200" height="600" title="by Sandra Lehecka"/>
            <div class="carousel-caption"></div>
        </div>
    </div><!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"></a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"></a>
</div>
<div class="text-center">
    <h1>{% projects_metadata 'title' %}</h1>
    <h3>{% projects_metadata 'subtitle' %}</h3>
    <p>{% projects_metadata 'description' %}</p>
    <p><small><strong>@ ACDH-OeAW staff</strong> go to <a href="https://redmine.acdh.oeaw.ac.at/issues/6848" target="_blank">Redmine</a> for log-in credentials.</small></p>
</div>

{% endblock %}